// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechnicalChallengeApp.DataRepository;

namespace TechnicalChallengeApp.DataRepository.Migrations
{
    [DbContext(typeof(CalculatorDbContext))]
    [Migration("20210428235310_AddLastTotalColumn")]
    partial class AddLastTotalColumn
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("TechnicalChallengeApp.DataRepository.Table.SessionData", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ButtonsPushed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastTotal")
                        .HasColumnType("INTEGER");

                    b.HasKey("SessionId");

                    b.ToTable("SessionData");
                });
#pragma warning restore 612, 618
        }
    }
}
